[program:magna_gestao-queue]
process_name=%(program_name)s_%(process_num)02d
directory=/srv/apps/php/magna_gestao
command=/usr/bin/php8.3 /srv/apps/php/magna_gestao/artisan queue:work --queue=automation,automation-import,integracoes,mail-receive,mail-process,mail-trip,mail-cte-return,default --sleep=3 --tries=3 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/srv/apps/php/magna_gestao/storage/logs/queue.log
stderr_logfile=/srv/apps/php/magna_gestao/storage/logs/queue_error.log

[program:magna_gestao-schedule]
process_name=%(program_name)s
directory=/srv/apps/php/magna_gestao
command=/usr/bin/php8.3 /srv/apps/php/magna_gestao/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/srv/apps/php/magna_gestao/storage/logs/schedule.log
stderr_logfile=/srv/apps/php/magna_gestao/storage/logs/schedule_error.log
